spring:
  datasource:
    url: jdbc:mysql://101.133.162.93:3306/temp?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "root"
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: application-dev
  redis:
    host: localhost
    port: 6379
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
server:
  port: 8080
logging:
  level:
    com:
      neusoft:
        newsroom: INFO
      mypackage:
        domain:
          persistence: DEBUG
    org:
      springframework:
        security: INFO
      hibernate: ERROR

#############################################################################
eureka:
  instance:
    prefer-ip-address: true
    #实例名
    instance-id: application-dev:${server.port}
  client:
    service-url:
      #euraka地址
      defaultZone: http://localhost:8763/eureka/

#############################################################################
feign:
  hystrix:
    enabled: false # 禁用超时
#hystrix 配置
hystrix:
  shareSecurityContext: true
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 100000
        forceClosed: true
      excution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
ribbon:
  #请求处理的超时时间
  ReadTimeout: 120000
  #请求连接的超时时间
  ConnectTimeout: 30000
#############################################################################
dirPath: C:\Users\chiu\Desktop\plamPass\Demo\Data\